// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgRk9sJh0wtR96RlQ6tN4oNyJFwowgiZM',
    appId: '1:979563682088:web:cff3e430d7e3d6e825981d',
    messagingSenderId: '979563682088',
    projectId: 'chat-app-ec6cc',
    authDomain: 'chat-app-ec6cc.firebaseapp.com',
    storageBucket: 'chat-app-ec6cc.appspot.com',
    measurementId: 'G-XR7721TQTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN7xwfwVzqIj7KamKRpAxLs7wjSnCLyqQ',
    appId: '1:979563682088:android:a26857da4348c25b25981d',
    messagingSenderId: '979563682088',
    projectId: 'chat-app-ec6cc',
    storageBucket: 'chat-app-ec6cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6-SnPgpAgikLCsJR-b2wyonkC2ql0w6o',
    appId: '1:979563682088:ios:e4420543daa8d83a25981d',
    messagingSenderId: '979563682088',
    projectId: 'chat-app-ec6cc',
    storageBucket: 'chat-app-ec6cc.appspot.com',
    iosClientId: '979563682088-re29t7mmuimp4vgvrm5j2eb0m8g1iu02.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6-SnPgpAgikLCsJR-b2wyonkC2ql0w6o',
    appId: '1:979563682088:ios:e4420543daa8d83a25981d',
    messagingSenderId: '979563682088',
    projectId: 'chat-app-ec6cc',
    storageBucket: 'chat-app-ec6cc.appspot.com',
    iosClientId: '979563682088-re29t7mmuimp4vgvrm5j2eb0m8g1iu02.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
